### ISSUE TITLE
Check calling rewards for missing items

### ISSUE THREAD

**Issue by kyatastrophe** [ThingEngineering/wowthing-again#410] opened 2022-06-16 06:57 UTC
Slands box toys, these things from bfa 
![image](https://user-images.githubusercontent.com/27977095/174008994-623ddfe1-c7d7-4fa1-9cb9-da9121c182bb.png)

prestige rewards from the rep and highlight all of the above on tooltip, etc

**Comment by madcowfred** [comment] 2022-06-25 19:10
Dupe of #398

**Closed by madcowfred** 2022-06-25 19:10 UTC
Labels: enhancement, area: frontend, area: data
