### ISSUE TITLE
Information not displayed

### ISSUE THREAD

**Issue by R41z0r** [ThingEngineering/wowthing-again#98] opened 2021-08-06 06:02 UTC
Hey there, nice site and project btw.

My characters are missing spec, gear, ilvl, cov lvl, actual weeks m+ run, progress - Is it possible, that you have a problem parsing data for Characters with special characters in name like: "Ð".

All the data from my "normal named" chars are working, but the others are missing. I was logged in for 5min in total on every char for testing and nothing appears after uploading data.
![Bildschirmfoto 2021-08-06 um 08 00 35](https://user-images.githubusercontent.com/6240199/128463586-d51273ed-847c-49a8-8b93-a1c7a73bc514.png)

**Comment by madcowfred** [comment] 2021-08-06 15:21
Oof, there was an issue with this in the old WoWthing also but I didn't have any characters to test with. I'll try making some and seeing if I can track down where the problem is.

**Comment by madcowfred** [comment] 2021-08-06 23:48
This is fixed now, rather weird bug - any non-ASCII character starting a name would break things because it couldn't convert it to lowercase (the API only takes lowercase character names). In this case "Ð" was meant to become "ð". Fun times!

**Closed by madcowfred** 2021-08-06 23:48 UTC
Labels: bug, area: backend
